[mdb]
url=""

[server]
bind-address=":8081"
mode="release"
rollbar-token=""
rollbar-environment="production"
base-url="https://cdn.kabbalahmedia.info/"

[file_service]
urls=[
  "http://files.kabbalahmedia.info/api/v1/get"
]
