version: "3.7"

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  postgres_feed:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - feed_pg_data:/var/lib/postgresql/data/pg_data
      - backup:/backup
    networks:
      - backend
    ports:
      - 5433:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pg_data
      POSTGRES_USER: ${FEED_USER}
      POSTGRES_PASSWORD: ${FEED_PASSWORD}
  feed_api:
    image: bneibaruch/feed_api:${FEED_API_VERSION}
    restart: unless-stopped
    volumes:
      - ./feed_api/config.toml:/app/config.toml
    networks:
      - frontend
      - backend
    extra_hosts:
      - nats.il.local:${HOST_NATS_IL_LOCAL}
    logging: *default-logging
    depends_on:
      - postgres_mdb
      - postgres_feed
      - elastic
    environment:
      MDB_URL: postgres://${MDB_USER}:${MDB_PASSWORD}@postgres_mdb/mdb?sslmode=disable
      MDB_LOCAL_URL: postgres://${FEED_USER}:${FEED_PASSWORD}@postgres_feed/mdb?sslmode=disable
      CHRONICLES_LOCAL_URL: postgres://${FEED_USER}:${FEED_PASSWORD}@postgres_feed/chronicles?sslmode=disable
      DATA_MODELS_URL: postgres://${FEED_USER}:${FEED_PASSWORD}@postgres_feed/data_models?sslmode=disable
      SERVER_ROLLBAR_TOKEN: ${ROLLBAR_TOKEN}
    command: ["/wait-for", "postgres_mdb:5432", "--", "/wait-for", "postgres_feed:5432", "--", "./feed-api", "server"]

networks:
  frontend:
    external:
      name: archive-docker_frontend
  backend:
    external:
      name: archive-docker_backend

volumes:
  feed_pg_data:

