[server]
bind-address=":8080"
mode="release"
rollbar-token=""
rollbar-environment="production"

[mdb]
url=""

[elasticsearch]
url="http://elastic:9200"
cdn-url="https://cdn.kabbalahmedia.info"
unzip-url="http://nginx/assets/api"
sources-folder="/assets/sources"
prepare-docs-batch-size=20
prepare-docs-parallelism=2
synonyms-folder="/assets/archive-backend/search/synonyms"

[nats]
url="nats://nats.il.local:4222"
client-id="mdb-test"
cluster-id="test-cluster"
subject="mdb"

[file_service]
url1="http://files.kabbalahmedia.info"

[assets_service]
url="http://nginx/assets/api/"

[cache]
refresh-search-stats="60s"

[cms]
url="https://kabbalahmedia.info/cms/wp-json/get-post-plugin/v1/"
image-url="kabbalahmedia.info/cms/wp-content/uploads/"
assets="/assets/cms/"
assets-images="/images/"