[server]
bind-address=":8080"
mode="release"
rollbar-token=""
rollbar-environment="production"

[mdb]
url=""

[elasticsearch]
url="http://elastic:9200"
cdn-url="https://cdn.kabbalahmedia.info"
unzip-url="http://nginx/assets/api"
data-folder="/app/data"
sources-folder="/assets/sources"
prepare-docs-batch-size=20
prepare-docs-parallelism=2
timeout-for-highlight="4s"
check-typo=true

[nats]
url="nats://nats.il.local:4222"
client-id="archive-backend-docker"
cluster-id="test-cluster"
subject="mdb"
durable=true
durable-name="archive-backend-events"

[file_service]
url1="http://files.kabbalahmedia.info"

[assets_service]
url="http://nginx/assets/api/"

[feed_service]
url="https://kabbalahmedia.info/feed_api/"

[content_unit_images]
url_template="https://kabbalahmedia.info/imaginary/thumbnail?url=http%%3A%%2F%%2Fnginx%%2Fassets%%2Fapi%%2Fthumbnail%%2F%s&width=140&stripmeta=true"

[cache]
refresh-search-stats="60s"

[cms]
url="https://kabbalahmedia.info/cms/wp-json/get-post-plugin/v1/"
image-url="kabbalahmedia.info/cms/wp-content/uploads/"
assets="/assets/cms/"
assets-images="/images/"
