[server]
bind-address=":8083"
mode="release"
rollbar-token=""
rollbar-environment="production"
boiler-mode=""

[mdb]
url=""

[elasticsearch]
url="http://elastic:9200"

[nats]
url="nats://nats.il.local:4222"
client-id="feed-api"
cluster-id="test-cluster"
subject="mdb"
durable=true
durable-name="feed-api-events"
