[server]
bind-address=":8083"
mode="release"
rollbar-token=""
rollbar-environment="production"
boiler-mode=""

[mdb]
url=""
local_url=""

[chronicles]
local_url=""
remote_api="https://chronicles.kli.one"

[data_models]
url=""
sqls_path="./databases/data_models/flow/"

[nats]
url="nats://nats.il.local:4222"
client-id="feed-api"
cluster-id="test-cluster"
subject="mdb"
durable=true
durable-name="feed-api-events"
